import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

import { SidebarNavigation } from '../components/SidebarNavigation'

type ContainerProps = {
  theme: string
}

const Container = styled.div<ContainerProps>` 
  padding: 0 20em;
  ${(props) => props.theme === 'dark' && 'background: black'}
`

const HomePage: NextPage = () => {
  return (
    <Container theme="light">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SidebarNavigation />
        <h1>Title here</h1>
      </main>

      <footer></footer>
    </Container>
  )
}

export default HomePage
